
DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO_MATRICULA VARCHAR(100) NOT NULL, NOMBRE VARCHAR(100) NOT NULL,APELLIDO VARCHAR(100) NOT NULL );

-- para test --
INSERT INTO ODONTOLOGOS(NUMERO_MATRICULA,NOMBRE, APELLIDO) VALUES ('884579', 'Paloma', 'Benitez'),('666667', 'Fernan', 'Lopez');